//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LantaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buying_Goods
    {
        public int ID_User { get; set; }
        public int ID_Type_Goods { get; set; }
        public int ID_Goods { get; set; }
        public int Count { get; set; }
    
        public virtual Corpus Corpus { get; set; }
        public virtual Disk Disk { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual Power_unit Power_unit { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual Type_Goods Type_Goods { get; set; }
        public virtual User User { get; set; }
        public virtual Video_card Video_card { get; set; }
    }
}
