//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LantaSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LantaSystemEntitiesBD : DbContext
    {
        public LantaSystemEntitiesBD()
            : base("name=LantaSystemEntitiesBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compatibility> Compatibility { get; set; }
        public virtual DbSet<Corpus> Corpus { get; set; }
        public virtual DbSet<Disk> Disk { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Power_unit> Power_unit { get; set; }
        public virtual DbSet<Processor> Processor { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Type_Disk> Type_Disk { get; set; }
        public virtual DbSet<Type_Goods> Type_Goods { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Video_card> Video_card { get; set; }
        public virtual DbSet<Buying_Goods> Buying_Goods { get; set; }
    }
}
