//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LantaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID_Payment { get; set; }
        public int Card_number { get; set; }
        public int Card_code { get; set; }
        public int ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
